#!/bin/bash -e

SERVICE_DIR=$(dirname $0)/service
PORT=$1

if [ -z "$PORT" ]; then
  echo "usage: $0 port_number" >&2
  exit 2
fi

NEW_SERVICE_DIR="$SERVICE_DIR/maintenance-$PORT"

if [ ! -e "$NEW_SERVICE_DIR" ]; then
  mkdir -p "$NEW_SERVICE_DIR"
  ln -s ../../maintenance-run $NEW_SERVICE_DIR/run
  echo "created maintenance service $NEW_SERVICE_DIR"
else
  echo "maintenance service $NEW_SERVICE_DIR already exists" >&2
  exit 1
fi
