#!/bin/bash -e

. ../../bootstrap
PORT=$(basename $(pwd)|awk -F- '{print $2}')
BASE=$(dirname $(readlink $0))

if [ -z "$PORT" ]; then
  echo "usage: $0 port" 1>&2;
  exit 2
fi

exec $(maybe_bundled maintenance_server) $PORT 2>&1
