#!/bin/bash -e

. ../../bootstrap
PORT=$(basename $(pwd)|awk -F- '{print $2}')

if [ -z "$PORT" ]; then
  echo "usage: $0 port" 1>&2;
  exit 2
fi

exec thin start -e production -p $PORT -c $APP_DIR 2>&1
