#!/bin/sh -e

PORT=$(basename $(pwd)|awk -F- '{print $2}')
BACKEND_PORT=$(basename $(pwd)|awk -F- '{print $3}')
USER=$(id -un)
BASE=$(dirname $(readlink $0))
APP_DIR=$($BASE/readlink_canonical $BASE/app)

if [ -e $BASE/varnishd ]; then
  VARNISHD=$BASE/varnishd
else
  VARNISHD=varnishd
fi

VARNISH_NAME="${USER}-${PORT}"
TEMP_BASE_DIR=/var/tmp/${USER}-varnish-${PORT}
if [ ! -d $TEMP_BASE_DIR ]; then
  mkdir -p $TEMP_BASE_DIR;
  chmod og-rwx $TEMP_BASE_DIR;
fi

cat <<EOF > varnish.conf
backend default {
  .host = "127.0.0.1";
  .port = "$BACKEND_PORT";
}

# only allow purging of cache from localhost
acl purge {
  "127.0.0.1";
}

sub vcl_recv {
  # The regex used here matches the standard rails cache buster urls
  # e.g. /images/an-image.png?1234567
  if (req.request == "GET" && req.url ~ "\.(css|js|jpg|jpeg|gif|ico|png)\??\d*$") {
    unset req.http.cookie;
  }
  elsif (req.http.cookie !~ "(_session_id|remember_user_token)=") {
    unset req.http.cookie;
  }

  if (req.request != "GET" && req.request != "HEAD") {
    if (req.request == "PURGE") {
      if (!client.ip ~ purge) {
        error 405 "Not allowed.";
      }
    }
  }
}

sub vcl_deliver {
  if (obj.hits > 0) {
    set resp.http.X-Cache = "HIT";
  } else {
    set resp.http.X-Cache = "MISS";
  }
}
EOF

exec $VARNISHD -a 127.0.0.1:$PORT -F -f varnish.conf -s file,$TEMP_BASE_DIR/data,200MB -n $VARNISH_NAME || echo "do you need to create the symlink '$BASE/varnishd?'"
